first makeover for mesher testing

diff --git a/scenario b/scenario
--- a/scenario
+++ b/scenario
@@ -41,7 +41,7 @@ for i in "${!VARARGS[@]}"; do
     ACTIVE_NODES="$ACTIVE_NODES ${VARARGS[$i]}"
 done
 
-LOG_FOLDER=/tmp/serval-monitor
+LOG_FOLDER=/tmp/mesher-monitor
 if [ -z ${LOCAL_LOG_FOLDER+x} ]; then LOCAL_LOG_FOLDER=$LOG_FOLDER-miniworld-$SCENARIO-`date +%Y-%m-%d_%H-%M`; fi
 mkdir -p $LOCAL_LOG_FOLDER
 
@@ -90,7 +90,7 @@ if [ "$TYPE" == "core" ]; then
         PIDS=""
         FAIL="0"
         for N in $1; do
-            vcmd -c ${NODES[$N]} -- sh -c "${@:2}" 1>&2 &
+            vcmd -c ${NODES[$N-1]} -- sh -c "${@:2}" 1>&2 &
             PIDS="$PIDS $!"
         done
         for PID in $PIDS; do
@@ -105,7 +105,7 @@ if [ "$TYPE" == "core" ]; then
         echo
         for N in $1; do
             echo -n -e "  Node $N: "
-            vcmd -c ${NODES[$N]} -- sh -c "${@:2}"
+            vcmd -c ${NODES[$N-1]} -- sh -c "${@:2}"
             echo
         done
     }
@@ -230,39 +230,49 @@ exec_seq "$ACTIVE_NODES" "$SCENARIO_FOLDER/prepare $NODE_CNT $ACTIVE_NODE_CNT $P
 ### PHASE 2
 export PHASE=12
 echo -n -e "\e[1;34mPhase 2 - Syncing qemu clocks\e[0m"
-echo "`date_ms`, 2, system-monitoring" >> $TIMING_FILE
-exec_par "$ALL_NODES" '/etc/init.d/sysntpd stop; killall ntpd ; mkdir -p /tmp/serval-monitor/ntp/ntp-log/; ntpd -c /etc/ntp.conf -q > /dev/null ; cp /tmp/ntp.log /tmp/serval-monitor/ntp/ntp-log/ntp_`hostname`.log'
+if [ "$TYPE" == "core" ]; then
+    echo " (not needed in CORE)."
+elif [ "$TYPE" == "miniworld" ]; then
+    echo "`date_ms`, 2, system-monitoring" >> $TIMING_FILE
+    exec_par "$ALL_NODES" '/etc/init.d/sysntpd stop; killall ntpd ; mkdir -p /tmp/serval-monitor/ntp/ntp-log/; ntpd -c /etc/ntp.conf -q > /dev/null ; cp /tmp/ntp.log /tmp/serval-monitor/ntp/ntp-log/ntp_`hostname`.log'
+fi
 
-echo -n -e "\e[1;34m        - Starting system monitoring\e[0m"
-exec_par "$ALL_NODES" "/serval-tests/monitor system"
+# echo -n -e "\e[1;34m        - Starting system monitoring\e[0m"
+# exec_par "$ALL_NODES" "/serval-tests/monitor system"
 
 ## PHASE 3
 export PHASE=13
-echo -n -e "\e[1;34mPhase 3 - Generating SIDs and starting servald\e[0m"
-echo "`date_ms`, 3, servald-start" >> $TIMING_FILE
-# exec_par "$ALL_NODES" 'export HOST=`hostname | cut -d u -f2`; printf "Host %i - %02x - " $HOST $((16 + $HOST)); servald keyring add "" `printf "%2x" $((16+$HOST))`; servald start > /dev/null; sleep 2'
-exec_par "$ALL_NODES" 'export HOST=`hostname | cut -d u -f2 | sed -e "s/^0*//g"`; servald keyring add "" `printf "%2x" $((16+$HOST))` > /dev/null; servald start > /dev/null; sleep 2'
+echo -n -e "\e[1;34mPhase 3 - Starting mesher\e[0m"
+echo "`date_ms`, 3, mesher-start" >> $TIMING_FILE
 
-## PHASE 3.1
-echo -n -e "\e[1;34m        - Collecting serval sids\e[0m"
-exec_seq "$ALL_NODES" "servald id self | tail -n1" | awk '{print $3}' | grep -v '^$' >> $SEVERAL_ALL_SIDS_FILE
-echo
+for N in $ALL_NODES; do
+    exec $N "nohup `which mesher-experimental` > $LOCAL_LOG_FOLDER/mesher-$N.log 2>&1 & echo \$! > mesher.pid; sleep 1" &
+    printf "."
+done
+echo 
 
-echo -n -e "\e[1;34m        - Distributing serval sids\e[0m"
-if [ "$TYPE" == "miniworld" ]; then
-    for N in $ALL_NODES; do
-        scp -q -r $SSH_OPTIONS $SEVERAL_ALL_SIDS_FILE ${NODES[$((N-1))]}:$SEVERAL_ALL_SIDS_FILE &
-        MYPIDS="$MYPIDS $!"
-    done
-    for PID in $MYPIDS; do
-        wait $PID || let "FAIL=$?"
-        printf .
-        if [ "$FAIL" != "0" ]; then echo -e "\e[1;31mPID $PID failed with $FAIL, aborting scenario.\e[0m"; exit $PHASE; fi
-    done
-    echo
-fi
 
-### PHASE 3.2
+
+# ## PHASE 3.1
+# echo -n -e "\e[1;34m        - Collecting serval sids\e[0m"
+# exec_seq "$ALL_NODES" "servald id self | tail -n1" | awk '{print $3}' | grep -v '^$' >> $SEVERAL_ALL_SIDS_FILE
+# echo
+#
+# echo -n -e "\e[1;34m        - Distributing serval sids\e[0m"
+# if [ "$TYPE" == "miniworld" ]; then
+#     for N in $ALL_NODES; do
+#         scp -q -r $SSH_OPTIONS $SEVERAL_ALL_SIDS_FILE ${NODES[$((N-1))]}:$SEVERAL_ALL_SIDS_FILE &
+#         MYPIDS="$MYPIDS $!"
+#     done
+#     for PID in $MYPIDS; do
+#         wait $PID || let "FAIL=$?"
+#         printf .
+#         if [ "$FAIL" != "0" ]; then echo -e "\e[1;31mPID $PID failed with $FAIL, aborting scenario.\e[0m"; exit $PHASE; fi
+#     done
+#     echo
+# fi
+
+#### PHASE 3.2
 #if [ "$TYPE" == "core" ]; then
 #    echo -n -e "\e[1;34m        - Initiating scan for other servald instances\e[0m"
 #    exec_seq "$ALL_NODES" 'for i in `ifconfig | grep "inet addr" | grep -v "127.0.0" | cut -d":" -f 2 | cut -d"." -f1,2,3`; do echo -n "$i.255: "; servald scan $i.255; done; exit 0'
@@ -271,11 +281,11 @@ fi
 #    exec_seq "$ALL_NODES" 'for i in `ifconfig | grep -A2 "eth" | grep "Bcast" | cut -d":" -f 2 | cut -d" " -f 1`; do echo -n "$i: "; servald scan $i; done; exit 0'
 #fi
 
-### PHASE 4
-export PHASE=14
-echo -n -e "\e[1;34mPhase 4 - Starting servald monitoring\e[0m"
-echo "`date_ms`, 4, servald-monitoring" >> $TIMING_FILE
-exec_par "$ALL_NODES" "/serval-tests/monitor serval"
+# ### PHASE 4
+# export PHASE=14
+# echo -n -e "\e[1;34mPhase 4 - Starting servald monitoring\e[0m"
+# echo "`date_ms`, 4, servald-monitoring" >> $TIMING_FILE
+# exec_par "$ALL_NODES" "/serval-tests/monitor serval"
 
 ### PHASE 5
 export PHASE=15
@@ -315,16 +325,20 @@ fi
 
 ### PHASE 8
 export PHASE=18
-echo -n -e "\e[1;34mPhase 8 - Stopping monitoring\e[0m"
-echo "`date_ms`, 8, stop-monitoring" >> $TIMING_FILE
-exec_par "$ALL_NODES" "/serval-tests/monitor stop; servald stop > /dev/null"
+echo -n -e "\e[1;34mPhase 8 - Stopping mesher\e[0m"
+echo "`date_ms`, 8, stop-mesher" >> $TIMING_FILE
+for N in $ALL_NODES; do
+    exec $N 'kill `cat mesher.pid`'
+    printf "."
+done
+echo
 
 ### PHASE 9
 export PHASE=19
 echo -n -e "\e[1;34mPhase 9 - Data Collection: \e[0m"
 echo "`date_ms`, 9, data-collection" >> $TIMING_FILE
 if [ "$TYPE" == "core" ]; then
-    echo "not needed in core, check /tmp/serval-monitor"
+    echo "not needed in core, check $LOCAL_LOG_FOLDER"
     
 elif [ "$TYPE" == "miniworld" ]; then
     echo -n "getting data using scp"
